baseurl = "http://bcdata.ca/2018"
relativeurls=false
canonifyurls=false

languageCode = "en-us"
title = "bcdata colloquium 18"
# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-hikari-theme"

#[permalinks]
#	post = "/:year/:month/:day/:slug"

[params]
	name = "bcdata.ca"
	description = "Data talks linking industry and the academy."
	copyright = "&copy; 2017 bcdata.ca -- All Rights Reserved."

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasnâ€™t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "bcdata colloquium"
	bio = "Data talks linking industry and the academy."
	subscribe = "Links"
	# followme = "Follow me on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/bcdataca"

	[[params.offcanvas.socialnetworks]]
		name = "IAM Workshop"
		url = "//workshop.bcdata.ca"

	[[params.offcanvas.socialnetworks]]
		name = "e-mail"
		url = "mailto:iam-workshop2017@lists.ubc.ca"